name: Deploy to Heroku

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to Heroku Production
        run: |
          git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/green2you-prod.git
          git push heroku HEAD:master -f
